#!/usr/bin/perl -w
use strict;
use DB_File;
# create an index of which hdrmd5 values are in which file
# call as
# BASEDIR=/home/bernhard/nobackup/opensuse/ ./indexhdrmd5

our $dbname = "hdrmd5.db";

sub get_pkgid($)
{ my $pkg = shift;
    return `rpm -qp --qf "%{PKGID}" $pkg`;
}

open(my $txtdb, ">>", "txtdb") or die "error opening txtdb for writing: $!";
my %hdrdata;
tie(%hdrdata, "DB_File", $dbname, O_RDWR|O_CREAT) or die "error opening DB: $!";
if($ENV{BASEDIR}) { chdir $ENV{BASEDIR} }

my @char = ("a".."z", "A".."Z", "0-9", "_", "-");

for my $firstchar (@char) { # trick to better use disk caches
  for my $secondchar (@char) { # trick to better use disk caches
    for my $pkg (glob("history/20*/tumbleweed/repo/oss/*/$firstchar$secondchar*.rpm")) {
	#my $pkg = "history/20190310/tumbleweed/repo/oss/x86_64/zziplib-devel-0.13.69-3.2.x86_64.rpm";
	my $pkgid = get_pkgid $pkg;
        next if $hdrdata{$pkgid}; # already in
        my $cid=`ipfs add -Q --raw-leaves $pkg`;
	print STDERR "$pkgid : $pkg\n";
	$hdrdata{$pkgid} = $pkg;
        print $txtdb "$pkgid $cid\n";
    }
  }
}
