#!/usr/bin/perl -w
use strict;
use DB_File;
# create an index of which hdrmd5 values are in which file
# call as
# export BASEDIR=/home/bernhard/nobackup/opensuse/ ; ( cd $BASEDIR && find history/ -name \*.rpm ) | rev | sort | rev | ./indexhdrmd5

our $dbname = "hdrmd5cid.db";

sub get_pkgid($)
{ my $pkg = shift;
    return `rpm -qp --nodigest --nosignature --qf "%{PKGID}" $pkg`;
}

open(my $txtdb, ">>", "${dbname}.txt") or die "error opening txtdb for writing: $!";
my %hdrdata;
tie(%hdrdata, "DB_File", $dbname, O_RDWR|O_CREAT) or die "error opening DB: $!";
if($ENV{BASEDIR}) { chdir $ENV{BASEDIR} }

while(my $pkg = <>) {
    chomp($pkg);
    #my $pkg = "history/20190310/tumbleweed/repo/oss/x86_64/zziplib-devel-0.13.69-3.2.x86_64.rpm";
    my $pkgid = get_pkgid $pkg;
    next if $hdrdata{$pkgid}; # already in
    my $cid=`ipfs add -n -Q --raw-leaves $pkg`; chomp($cid);
    die unless $cid;
    print STDERR "$pkgid : $cid : $pkg\n";
    $hdrdata{$pkgid} = $cid;
    print $txtdb "$pkgid $cid $pkg\n";
}
