#!/bin/bash
d=~/.ipfs/bmw/opensuse
: ${old:=false}
addobj=$1 #QmZxqNMLtxgSWtombH5Ade8zspWoT7BxtFUMvxCyDmekpC
addobjt=$(basename $(ipfs resolve /ipfs/$addobj/tumbleweed))
[[ -n "$addobjt" ]] || exit 21
addname=$(cut -c12-19 /ipfs/$addobj/tumbleweed/repo/oss/media.1/products) #20190310
head=`cat $d/head`
newhead=$(ipfs --upgrade-cidv0-in-output object patch add-link $head history/$addname $addobj)
(ipfs ls --size=false --resolve-type=false /ipfs/$newhead/history/ | perl -pe 's/^[^ ]+ *(.*)/$1/' | tac | grep 20) > ~/nobackup/opensuse/history/list
addobjlist=$(ipfs add -Q --raw-leaves ~/nobackup/opensuse/history/list)
newhead=$(ipfs --upgrade-cidv0-in-output object patch add-link $newhead history/list $addobjlist)
#$old || newhead=$(ipfs object patch rm-link $newhead current)
$old || newhead=$(ipfs --upgrade-cidv0-in-output object patch add-link $newhead tumbleweed $addobjt)
[[ -n "$newhead" ]] || exit 22
#too slow:ipfs pin update $head $newhead
$old || ipfs pin add --recursive=false $newhead
$old || ipfs pin add --recursive=false $newhead/history
#mv $d/head{,.$addname}
date "+$head %Y-%m-%dT%H:%M:%S" >> $d/reflog
echo $newhead > $d/head
$old && exit 0
fusermount -u /ipns || :
#ipfs name publish /ipfs/$newhead
cd ~/code/cvs/dynaname && TXTRECORD="dnslink=/ipfs/$newhead" ./dynaname -4 -S vm2c.zq1.de. -H tumbleweedipfs.d.zq1.de
l=/home/bernhard/.ipfs/ipns/opensuse.zq1.de
rm -f $l
ln -s /ipfs/$newhead $l
ipfs name publish $newhead
# => /ipns/QmT7bZwZ3gpBMswUBjtpFhPM42ErFapAPiQHM2ELu3deqs
#ipfs name publish --key=tumbleweed $newhead
# => /ipns/QmWYH4XmxSqwzV1DdqJPgwMrhAABZWPoSe4USjwJdkaAQy
